---
title: "AMRrules timings"
output: html_document
date: "2026-10-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

``` {r}
times <- read_tsv("AMRrules_timings.tsv") %>% 
  mutate(organism = case_when(organism=="Abaumannii" ~ "A. baumannii",
                              organism=="Cjejuni" ~ "C. jejuni",
                              organism=="Ecoli" ~ "E. coli",
                              organism=="Efaecalis" ~ "E. faecalis",
                              organism=="Efaecium" ~ "E. faecium",
                              organism=="Kpneumoniae" ~ "K. pneumoniae",
                              organism=="Ngono" ~ "N. gonorrhoeae",
                              organism=="Paeruginosa" ~ "P. aeruginosa",
                              organism=="Saureus" ~ "S. aureus",
                              organism=="Senterica" ~ "S. enterica"
                              ))

# shape of runtime curve per organism
linear_per_orgn <- times %>% ggplot(aes(x=size, y=elapsed_sec, colour=organism)) + geom_point() + geom_smooth(method = "lm", se = FALSE, linewidth=0.5) + theme_bw() + labs(x="No. samples", y="Time (s)", colour="Organism", title="a) Runtime vs number of samples, stratified by organism") 

# impact of number of markers on runtime, within each organism (which each have a unique but fixed rule count)
not_linear_per_marker_withinorg <- times %>% 
  filter(size==1000) %>% 
  ggplot(aes(x=amr_marker_count, y=elapsed_sec, group=organism)) + 
  geom_point(aes(colour=organism)) + 
  geom_smooth(method = "lm", se = FALSE, colour="black", linewidth=0.5) + 
  theme_bw() +
  theme(legend.position="none") + 
  xlim(c(0,20000)) + ylim(1.8,4)+
  labs(x="No. AMR markers", y="Time (s)", title="c) Runtime vs no. AMR markers", subtitle="for subsets of n=1000 samples")

# summarise times one row per organism
org_summary <- times %>%
    filter(status == 0 & size==1000) %>%
    group_by(organism, n_rules) %>%
    summarise(
        sec_per_1000 = mean(elapsed_sec),
        .groups = "drop"
    )

# time vs number of rules, for subsets of 1000 samples
lm_time_rules <- lm(sec_per_1000 ~ n_rules, data=org_summary)

summary(lm_time_rules)

time_rules <- coef(lm_time_rules)

associated_rulecount <- org_summary %>% ggplot(aes(x=n_rules, y=sec_per_1000, label=organism, colour=organism)) + 
  geom_abline(intercept=time_rules[["(Intercept)"]], slope=time_rules[["n_rules"]], linetype=2, colour="grey") + 
  geom_point() + 
  geom_text(hjust=-0.1, size = 3) +
  theme_bw() +
  theme(legend.position="none") + 
  xlim(c(0,500)) + ylim(1.8,4)+
  labs(x="No. rules defined", y="Time (s)", title="b) Runtime vs no. rules defined", subtitle="for subsets of n=1000 samples")
  

(linear_per_orgn / ( associated_rulecount + not_linear_per_marker_withinorg)) + plot_layout(guides="collect")
```

``` {r}
ggsave("Runtime_figure.pdf", width=10.5, height=8)
ggsave("Runtime_figure.png", width=10.5, height=8)
```

# regression lines
``` {r} 
regressions <- times %>% 
  filter(size==1000) %>%
  group_by(organism) %>%
  summarise({
    mod <- lm(elapsed_sec ~ amr_marker_count)
    tibble(
      slope = coef(mod)[["amr_marker_count"]],
      r.squared = summary(mod)$r.squared,
      p.value = summary(mod)$coefficients["amr_marker_count", "Pr(>|t|)"]
    )
  })

write_tsv(regressions, "Additional_file_6_regressions.tsv")
```
